### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by kyeonkim** [kyeonkim/backend-develop-onboarding-project2#2]
# TODO

- [ ] 유저 생성 시 DB에 저장
- [ ] 저장 시 비밀번호 암호화
- [ ] 중복된 이름, 닉네임으로는 가입 불가
- [ ] 생성 시 기본 권한(ROLE_USER) 부여

# Request Template
```
{
	"username": "kyeonkim",
	"password": "12341234",
	"nickname": "man"
}
```

# Response Template
```
{
	"username": "kyeonkim",
	"nickname": "man",
	"authorities": [
	    {
                "authorityName": "ROLE_USER"
	    }
	]
}
```

# 테스트 TODO

- [ ] 유저가 정상적을 생성되었는가?
- [ ] 저장 시 비밀번호가 암호화가 되는가?
- [ ] 생성 시 기본 권한이 부여되는가?
- [ ] 중복된 이름과 닉네임으로 가입이 안되는가?
