### ISSUE TITLE
AWS EC2 배포

### ISSUE THREAD

**Issue by kyeonkim** [kyeonkim/backend-develop-onboarding-project2#4]
# ToDo

- [ ] AWS EC2에 배포 진행
- [ ] /signup, /sign api 테스트 진행

# 테스트 TODO
- [ ] 배포가 정상적으로 되었는가?
- [ ] 배포 환경에서 회원가입이 정상적으로 되는가? 
- [ ] 배포 환경에서 로그인 시 acess, refresh token이 정상적으로 발급되었는가?
