### ISSUE TITLE
Swagger UI를 통한 API 접근과 검증

### ISSUE THREAD

**Issue by kyeonkim** [kyeonkim/backend-develop-onboarding-project2#5]
# ToDo

- [ ] Swagger UI 추가
- [ ] Swagger UI를 통해 API 접근 및 검증하기

# 테스트 TODO
- [ ] Swagger가 정상적으로 동작하는가?
